let colors = require('tailwindcss/colors')

module.exports = {
  content: ["./src/**/*.{html,js,tsx}"],
  darkMode: 'media', // or 'class'
  theme: {
    extend: {
      // colors: {
      //   // primary:  {
      //   inherit: colors.inherit,
      //   current: colors.current,
      //   transparent: colors.transparent,
      //   blacker: colors.black,
      //   white: colors.white,
      //   slate: colors.slate,
      //   gray: colors.gray,
      //   zinc: colors.zinc,
      //   neutral: colors.neutral,
      //   stone: colors.stone,
      //   red: {
      //     default: colors.red['400'],
      //     light: colors.red['100'],
      //     dark: colors.red['700'],
      //   },
      //   orange: colors.orange,
      //   amber: colors.amber,
      //   yellow: colors.yellow,
      //   lime: colors.lime,
      //   green: {
      //     default: colors.green['400'],
      //     light: colors.green['100'],
      //     dark: colors.green['700'],
      //   },
      //   emerald: colors.emerald,
      //   teal: colors.teal,
      //   cyan: colors.cyan,
      //   sky: colors.sky,
      //   blue: colors.blue,
      //   indigo: colors.indigo,
      //   violet: colors.violet['600'],
      //   purple: colors.purple,
      //   fuchsia: colors.fuchsia,
      //   pink: colors.pink,
      //   rose: colors.rose,
      //   // },
      //   // custom: {
      //   //   inherit: colors.inherit,
      //   //   current: colors.current,
      //   //   transparent: colors.transparent,
      //   //   black: colors.black,
      //   //   white: colors.white,
      //   //   slate: colors.slate,
      //   //   gray: colors.gray,
      //   //   zinc: colors.zinc,
      //   //   neutral: colors.neutral,
      //   //   stone: colors.stone,
      //   //   red: colors.red,
      //   //   orange: colors.orange,
      //   //   amber: colors.amber,
      //   //   yellow: colors.yellow,
      //   //   lime: colors.lime,
      //   //   green: colors.green,
      //   //   emerald: colors.emerald,
      //   //   teal: colors.teal,
      //   //   cyan: colors.cyan,
      //   //   sky: colors.sky,
      //   //   blue: colors.blue,
      //   //   indigo: colors.indigo,
      //   //   violet: colors.violet,
      //   //   purple: colors.purple,
      //   //   fuchsia: colors.fuchsia,
      //   //   pink: colors.pink,
      //   //   rose: colors.rose,
      //   // },
      //   // "primary-green": "#00ff16",
      //   // "evil-red": withOpacityValue('--color-secondary'),
      //   // "evil-blue": withOpacityValue('--color-evil-blue'),
      // }
    },
  },
}
